title: "Anirudh Ramji"
description: "Musings on backend, AI, and poetic pipelines."
url: "https://ac259.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

header:
  nav: "main"

collections:
  pages:
    output: true
    permalink: /:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/


defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: false
      show_date: false
      share: false
      related: false
      comments: false
      prev_next: false

  - scope:
      path: ""
      type: posts
    values:
      layout: single
      sidebar:
        nav: false
      author_profile: false

sass:
  style: compressed

author:
  name: "Anirudh Ramji"
  bio: "My musings and journey. Figured I'd write about it - probably will read it myself."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:ramji.anirudh@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ac259"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/anirudh-c-ramji/"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/yourhandle"

footer:
  footer_scripts:
    - /assets/js/theme-toggle.js
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ac259"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/anirudh-c-ramji/"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/yourhandle"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:ramji.anirudh@gmail.com"


plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-remote-theme
