title: "The Remains of the Code"
description: "Musings on backend, AI, and poetic pipelines."
url: "https://ac259.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      sidebar:
        nav: false

sass:
  style: compressed

author:
  name: "Anirudh Ramji"
  bio: "My musings and journey. Figured I'd write about it - probably will read it myself."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:ramji.anirudh@gmail.com"


plugins:
  - jekyll-include-cache
